name: Pymathics-natlang (Consistency Checks)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        python -m pip install pytest
        # Can comment out when next Mathics3 core and Mathics-scanner are released
        python -m pip install -e git+https://github.com/Mathics3/mathics-scanner#egg=Mathics-Scanner[full]
        python -m pip install -e git+https://github.com/Mathics3/mathics-core#egg=Mathics3[full]
        (cd src/mathics3 && bash ./admin-tools/make-JSON-tables.sh)
        # python -m pip install Mathics3[full]
    - name: Install Pymathics.natlang
      run: |
        make develop
    - name: Test Mathics Consistency and Style
      run: |
        make check-consistency-and-style
