name: Pymathics-natlang (Consistency Checks)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        python -m pip install pytest
        # Can comment out when next Mathics3 core and Mathics-scanner are released
        # python -m pip install -e git+https://github.com/Mathics3/mathics-scanner#egg=Mathics-Scanner[full]
        # git clone https://github.com/Mathics3/mathics-core
        # (cd mathics-core && make)
        # (cd mathics-core && python -m pip install -e .[full])
        python -m pip install Mathics
    - name: Install Pymathics.natlang
      run: |
        make develop
    - name: Test Mathics Consistency and Style
      run: |
        make check-consistency-and-style
