name: pymathics-natlang (macOS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      LDFLAGS: "-L/usr/local/opt/llvm@11/lib"
      CPPFLAGS: "-I/usr/local/opt/llvm@11/include"
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macOS]
        python-version: ['3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        brew install llvm@11
        python -m pip install --upgrade pip
        LLVM_CONFIG=/usr/local/Cellar/llvm@11/11.1.0/bin/llvm-config pip install llvmlite
        brew install mariadb
        pip install pytest
        # Can comment out when next Mathics core and Mathics-scanner are released
        python -m pip install -e git+https://github.com/Mathics3/mathics-scanner#egg=Mathics-Scanner[full]
        # Can remove after next Mathics-core release
        python -m pip install -e git+https://github.com/Mathics3/mathics-core#egg=Mathics3[full]
        (cd src/mathics3 && bash ./admin-tools/make-op-tables.sh)
        # python -m pip install Mathics3[full]
    - name: Install pymathics.natlang
      run: |
        pip install -e .
    - name: Test natlang
      run: |
        make check
