name: pymathics-natlang (macOS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '**'

jobs:
  build:
    env:
      LDFLAGS: "-L/opt/homebrew/opt/llvm/lib/c++ -L/opt/homebrew/opt/llvm/lib -lunwind"
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macOS]
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OS dependencies
      run: |
        brew update
        brew install enchant
        brew install llvm tesseract enchant mysql
        python -m pip install --upgrade pip
        pip install pytest pyenchant
        PYENCHANT_VERBOSE_FIND=1 python -c 'import enchant'

        # LLVM_CONFIG=/usr/local/Cellar/llvm@18/18.1.8/bin/llvm-config pip install llvmlite
        # Can comment out when next Mathics core and Mathics-scanner are released
        # python -m pip install -e git+https://github.com/Mathics3/mathics-scanner#egg=Mathics-Scanner[full]
        # Can remove after next Mathics-core release
        python -m pip install -e git+https://github.com/Mathics3/mathics-core#egg=Mathics3[full]
        (cd src/mathics3 && bash ./admin-tools/make-op-tables.sh)
        # python -m pip install Mathics3[full]
    - name: Install pymathics.natlang
      run: |
        make develop
    - name: Test natlang
      run: |
        make check
