name: pymathics.natlang (Ubuntu)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Ensure setuptools is installed
      run: python -m pip install --upgrade pip setuptools>=70.0.0 wheel    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        # Go over and comment out stuff when next Mathics core and Mathics-scanner are released
        # python -m pip install -e git+https://github.com/Mathics3/mathics-scanner#egg=Mathics-Scanner[full]
        # git clone https://github.com/Mathics3/mathics-core
        # (cd mathics-core && pip3 install -e .[full])
        # (cd mathics-core && bash ./admin-tools/make-JSON-tables.sh)
        # python -m pip install -e git+https://github.com/Mathics3/Mathics3-Module-Base#egg=Mathics3-Module-Base
    - name: Install Mathics3 natlang Module
      run: |
        python -m pip install --no-build-isolation setuptools Mathics3[full] nltk PatternLite enchant
        make develop
    - name: Test natlang Mathics3 Module
      run: |
        make -j3 check
